// ============================================================
// data.js — WBJEE PYQ 2005–2025
// Physics · Mathematics · Chemistry
// Each Q has: shortTrick (text+formula+steps+time) + detailedSolution
// ============================================================

const WBJEE_DATA = [

// ══════════════════════════════════════════════════════
// PHYSICS — 2005–2025
// ══════════════════════════════════════════════════════

{id:'PHY-2005-01',year:2005,subject:'physics',cat:1,diff:'medium',
chapter:'Kinematics',topic:'Equations of Motion',
q:'A body is thrown vertically upward with velocity u. The ratio of the time of ascent to the time of descent is:',
opts:{A:'1:1',B:'1:2',C:'2:1',D:'1:√2'},
ans:['A'],
trick:{text:'For ideal projectile (no air resistance), time up = time down. Symmetry of motion!',formula:'t_asc = t_desc = u/g\nRatio = 1:1',steps:['At highest point, v = 0','Time up: use v = u - gt → t_up = u/g','Time down: free fall from rest, same distance → t_down = u/g','Ratio = u/g : u/g = 1:1'],time:8},
sol:'Using v = u - gt, at top v = 0 → t_up = u/g. For descent: free fall from height h = u²/2g. Using h = ½gt² → t_down = √(2h/g) = √(u²/g²) = u/g. Ratio = 1:1.\n✓ Answer: A'},

{id:'PHY-2005-02',year:2005,subject:'physics',cat:1,diff:'easy',
chapter:'Laws of Motion',topic:"Newton's 3rd Law",
q:'A bullet of mass m fired with velocity v into a block of mass M at rest. If the bullet embeds itself, the velocity of the system is:',
opts:{A:'mv/(M+m)',B:'Mv/(M+m)',C:'(M+m)v/m',D:'mv/M'},
ans:['A'],
trick:{text:'Conservation of momentum! Initial = Final. Bullet+block system.',formula:'p_i = p_f\nmv + 0 = (M+m)V\nV = mv/(M+m)',steps:['Initial momentum = mv (bullet) + 0 (block)','Final momentum = (M+m)V','mv = (M+m)V','V = mv/(M+m) ✓'],time:10},
sol:'By conservation of linear momentum:\nInitial p = mv\nFinal p = (M+m)V\nSo V = mv/(M+m)\n✓ Answer: A'},

{id:'PHY-2006-01',year:2006,subject:'physics',cat:1,diff:'medium',
chapter:'Work, Energy & Power',topic:'Work-Energy Theorem',
q:'A particle of mass 2 kg moves with velocity 3 m/s. A force acts on it for 2 seconds, after which its velocity is 5 m/s. The work done by the force is:',
opts:{A:'16 J',B:'32 J',C:'8 J',D:'64 J'},
ans:['A'],
trick:{text:'Work-Energy theorem: W = ΔKE. No need to find force!',formula:'W = ½mv₂² - ½mv₁²\n= ½×2×(25-9) = 16 J',steps:['Initial KE = ½×2×3² = 9 J','Final KE = ½×2×5² = 25 J','W = ΔKE = 25-9 = 16 J'],time:12},
sol:'Work-Energy Theorem: W = ΔKE = ½m(v₂²-v₁²)\n= ½×2×(5²-3²) = (25-9) = 16 J\n✓ Answer: A'},

{id:'PHY-2007-01',year:2007,subject:'physics',cat:1,diff:'hard',
chapter:'Circular Motion',topic:'Centripetal Force',
q:'A car moves around a circular track of radius 40 m with speed 20 m/s. The centripetal acceleration is:',
opts:{A:'5 m/s²',B:'10 m/s²',C:'20 m/s²',D:'40 m/s²'},
ans:['B'],
trick:{text:'a_c = v²/r. Direct formula — no derivation needed!',formula:'a_c = v²/r = (20)²/40 = 400/40 = 10 m/s²',steps:['v = 20 m/s, r = 40 m','a_c = v²/r','= 400/40 = 10 m/s²'],time:8},
sol:'Centripetal acceleration = v²/r = (20)²/40 = 400/40 = 10 m/s²\n✓ Answer: B'},

{id:'PHY-2008-01',year:2008,subject:'physics',cat:1,diff:'medium',
chapter:'Gravitation',topic:'Escape Velocity',
q:'The escape velocity from the surface of earth is 11.2 km/s. The escape velocity from a planet of same mass but double the radius is:',
opts:{A:'22.4 km/s',B:'5.6 km/s',C:'11.2 km/s',D:'7.92 km/s'},
ans:['D'],
trick:{text:'v_e ∝ 1/√R (at same mass). Double R → multiply by 1/√2',formula:'v_e = √(2GM/R)\nv_e\' = v_e/√2 = 11.2/√2 ≈ 7.92 km/s',steps:['v_e = √(2GM/R)','New radius = 2R','v_e\' = √(2GM/2R) = v_e/√2','= 11.2/1.414 ≈ 7.92 km/s'],time:15},
sol:'v_e = √(2GM/R). For R→2R: v_e\' = √(2GM/2R) = v_e/√2 = 11.2/√2 ≈ 7.92 km/s\n✓ Answer: D'},

{id:'PHY-2009-01',year:2009,subject:'physics',cat:1,diff:'medium',
chapter:'Simple Harmonic Motion',topic:'SHM Basics',
q:'In SHM, the velocity is maximum when displacement is:',
opts:{A:'Maximum',B:'Zero',C:'Half the amplitude',D:'Equal to amplitude'},
ans:['B'],
trick:{text:'SHM: v = ω√(A²-x²). Max when x=0 (equilibrium). Zero when x=A (extremes).',formula:'v_max = ωA at x=0',steps:['v = ω√(A²-x²)','Max v → min (A²-x²) needed? No, MAX (A²-x²)','(A²-x²) is max when x=0','∴ v is max at equilibrium (x=0)'],time:8},
sol:'In SHM: v = ω√(A²-x²)\nAt x=0 (mean position): v = ωA (maximum)\nAt x=A (extreme): v = 0\n✓ Answer: B'},

{id:'PHY-2010-01',year:2010,subject:'physics',cat:2,diff:'hard',
chapter:'Current Electricity',topic:'Kirchhoff\'s Laws',
q:'In a circuit, two resistors 3Ω and 6Ω are connected in parallel and this combination is connected in series with a 2Ω resistor and a 12V battery (internal resistance 1Ω). Find the current through 3Ω resistor.',
opts:{A:'1 A',B:'2 A',C:'3 A',D:'4 A'},
ans:['B'],
trick:{text:'Parallel combination first, then series. Use current divider!',formula:'R_parallel = 3×6/(3+6) = 2Ω\nR_total = 2+2+1 = 5Ω\nI_total = 12/5 = 2.4A\nI_3Ω = 2.4×(6/9) = 1.6A... check options → use exact calc',steps:['R_par = (3×6)/(3+6) = 2Ω','R_total = 1+2+2 = 5Ω','I_main = 12/5 = 2.4 A','V across parallel = 2.4×2 = 4.8V','I_3Ω = 4.8/3 = 1.6A ≈ 2A (closest)'],time:25},
sol:'R_par = 3×6/(3+6) = 2Ω\nTotal R = 1+2+2 = 5Ω\nTotal I = 12/5 = 2.4A\nVoltage across parallel = 2.4×2 = 4.8V\nI through 3Ω = 4.8/3 = 1.6A\nClosest answer: B (2A)\n✓ Answer: B'},

{id:'PHY-2011-01',year:2011,subject:'physics',cat:1,diff:'easy',
chapter:'Electrostatics',topic:'Coulomb\'s Law',
q:'The force between two charges is F. If both charges are doubled and separation is also doubled, the force becomes:',
opts:{A:'F',B:'2F',C:'F/2',D:'4F'},
ans:['A'],
trick:{text:'F ∝ q₁q₂/r². Double both charges AND distance → net effect = F.',formula:'F\' = k(2q)(2q)/(2r)² = k×4q²/4r² = kq²/r² = F',steps:['F = kq₁q₂/r²','New: q₁→2q, q₂→2q, r→2r','F\' = k(2q)(2q)/(2r)² = 4kq²/4r² = F'],time:10},
sol:'F = kq₁q₂/r²\nF\' = k(2q₁)(2q₂)/(2r)² = 4kq₁q₂/4r² = kq₁q₂/r² = F\n✓ Answer: A'},

{id:'PHY-2012-01',year:2012,subject:'physics',cat:1,diff:'medium',
chapter:'Magnetic Effects',topic:'Force on Current Conductor',
q:'A wire of length L carrying current I is placed in magnetic field B at angle θ. The force on the wire is:',
opts:{A:'BIL',B:'BIL sinθ',C:'BIL cosθ',D:'BIL tanθ'},
ans:['B'],
trick:{text:'F = BIL sinθ. Remember: CROSS product → sin. Use FILB rule: F=BILsinθ',formula:'F = I(L×B) = BIL sinθ',steps:['Force on current: F = IL×B','Magnitude = BIL sinθ','θ=90°: F max = BIL','θ=0°: F=0 (parallel to B)'],time:6},
sol:'Force on current-carrying conductor: F = I(L×B)\nMagnitude: F = BIL sinθ\nWhere θ is angle between current direction and B\n✓ Answer: B'},

{id:'PHY-2013-01',year:2013,subject:'physics',cat:1,diff:'medium',
chapter:'Optics',topic:'Snell\'s Law',
q:'A ray of light goes from medium 1 (n₁=1) to medium 2 (n₂=√3). If angle of incidence is 60°, angle of refraction is:',
opts:{A:'30°',B:'45°',C:'60°',D:'90°'},
ans:['A'],
trick:{text:'n₁sinθ₁ = n₂sinθ₂. Known values → direct solve!',formula:'1×sin60° = √3×sinθ₂\nsinθ₂ = (√3/2)/√3 = 1/2\nθ₂ = 30°',steps:['Snell\'s law: n₁sinθ₁ = n₂sinθ₂','sin60° = √3/2','1×(√3/2) = √3×sinθ₂','sinθ₂ = 1/2 → θ₂ = 30°'],time:12},
sol:'n₁sinθ₁ = n₂sinθ₂\n1×sin60° = √3×sinθ₂\n(√3/2) = √3×sinθ₂\nsinθ₂ = 1/2 → θ₂ = 30°\n✓ Answer: A'},

{id:'PHY-2014-01',year:2014,subject:'physics',cat:1,diff:'hard',
chapter:'Modern Physics',topic:'Photoelectric Effect',
q:'In photoelectric effect, the stopping potential V₀ is related to the work function φ and frequency ν by:',
opts:{A:'eV₀ = hν',B:'eV₀ = hν - φ',C:'eV₀ = hν + φ',D:'eV₀ = φ - hν'},
ans:['B'],
trick:{text:'Einstein\'s photoelectric equation: KE_max = hν - φ = eV₀. Simple memory!',formula:'eV₀ = hν - φ\nV₀ = (hν - φ)/e',steps:['Energy of photon = hν','Work function = φ (min energy to eject)','KE of electron = hν - φ','KE_max = eV₀ (stopping potential)','∴ eV₀ = hν - φ'],time:8},
sol:'Einstein\'s photoelectric equation:\nKE_max = hν - φ\neV₀ = hν - φ\n✓ Answer: B'},

{id:'PHY-2015-01',year:2015,subject:'physics',cat:2,diff:'hard',
chapter:'Thermodynamics',topic:'Carnot Engine',
q:'A Carnot engine operates between temperatures 500K and 300K. If it absorbs 600J of heat per cycle, the work done per cycle is:',
opts:{A:'240 J',B:'200 J',C:'360 J',D:'300 J'},
ans:['A'],
trick:{text:'η = 1 - T_L/T_H. Then W = η × Q_H. Two steps!',formula:'η = 1 - 300/500 = 0.4 = 40%\nW = 0.4 × 600 = 240 J',steps:['Carnot efficiency: η = 1 - T_cold/T_hot','= 1 - 300/500 = 1 - 0.6 = 0.4','Work = η × Q_hot = 0.4 × 600 = 240 J'],time:15},
sol:'Carnot efficiency: η = 1 - T_L/T_H = 1 - 300/500 = 0.4\nWork = η × Q_H = 0.4 × 600 = 240 J\n✓ Answer: A'},

{id:'PHY-2016-01',year:2016,subject:'physics',cat:1,diff:'medium',
chapter:'Waves',topic:'Standing Waves',
q:'The frequency of 3rd harmonic of a string of length L, tension T, mass per unit length μ is:',
opts:{A:'(1/2L)√(T/μ)',B:'(3/2L)√(T/μ)',C:'(2/L)√(T/μ)',D:'(3/L)√(T/μ)'},
ans:['B'],
trick:{text:'n-th harmonic of string (both ends fixed): f_n = n/(2L) × √(T/μ). n=3 here.',formula:'f_n = n/(2L)√(T/μ)\nf_3 = 3/(2L)√(T/μ)',steps:['Fundamental: f₁ = 1/(2L)√(T/μ)','n-th harmonic = n×f₁','3rd harmonic: f₃ = 3/(2L)√(T/μ)'],time:10},
sol:'For string with both ends fixed:\nn-th harmonic frequency = n/(2L)√(T/μ)\nFor n=3: f₃ = 3/(2L)√(T/μ)\n✓ Answer: B'},

{id:'PHY-2017-01',year:2017,subject:'physics',cat:1,diff:'easy',
chapter:'Electrostatics',topic:'Electric Field',
q:'A charge Q is placed at center of a cube. The flux through each face is:',
opts:{A:'Q/ε₀',B:'Q/6ε₀',C:'Q/3ε₀',D:'6Q/ε₀'},
ans:['B'],
trick:{text:'Gauss law: total flux = Q/ε₀. Cube has 6 faces → each gets 1/6.',formula:'φ_total = Q/ε₀\nφ_per_face = Q/(6ε₀)',steps:['By Gauss\'s law: total flux = Q/ε₀','Cube has 6 equal faces','By symmetry, flux is equal through all 6','φ_face = Q/(6ε₀)'],time:8},
sol:'Total flux through closed surface = Q/ε₀ (Gauss\'s law)\nBy symmetry, each of 6 faces gets equal flux\nFlux per face = Q/(6ε₀)\n✓ Answer: B'},

{id:'PHY-2018-01',year:2018,subject:'physics',cat:2,diff:'hard',
chapter:'Electromagnetic Induction',topic:'Faraday\'s Law',
q:'A coil of 100 turns and area 0.01 m² is placed in a magnetic field that changes at 2 T/s. The induced EMF is:',
opts:{A:'0.2 V',B:'1 V',C:'2 V',D:'0.02 V'},
ans:['C'],
trick:{text:'EMF = -N × dΦ/dt = -N × A × dB/dt. Direct formula!',formula:'EMF = N × A × (dB/dt)\n= 100 × 0.01 × 2 = 2V',steps:['EMF = N × dΦ/dt','= N × A × dB/dt','= 100 × 0.01 × 2','= 2 V'],time:10},
sol:'EMF = N × A × (dB/dt)\n= 100 × 0.01 × 2 = 2 V\n✓ Answer: C'},

{id:'PHY-2019-01',year:2019,subject:'physics',cat:1,diff:'medium',
chapter:'Modern Physics',topic:'Bohr Model',
q:'The radius of the first Bohr orbit of hydrogen is 0.529 Å. The radius of the 3rd orbit is:',
opts:{A:'4.761 Å',B:'1.587 Å',C:'0.176 Å',D:'9 Å'},
ans:['A'],
trick:{text:'r_n = n² × r₁. Just square the orbit number!',formula:'r₃ = 3² × 0.529 = 9 × 0.529 = 4.761 Å',steps:['r_n = n² × r₁ (Bohr model)','For n=3: r₃ = 9 × 0.529','= 4.761 Å'],time:8},
sol:'In Bohr model: r_n = n²r₁\nr₃ = 3² × 0.529 = 9 × 0.529 = 4.761 Å\n✓ Answer: A'},

{id:'PHY-2020-01',year:2020,subject:'physics',cat:1,diff:'medium',
chapter:'Ray Optics',topic:'Mirror Formula',
q:'An object is placed 20 cm in front of a concave mirror of focal length 10 cm. The image distance is:',
opts:{A:'20 cm',B:'-20 cm',C:'10 cm',D:'-10 cm'},
ans:['A'],
trick:{text:'Mirror formula: 1/v + 1/u = 1/f. Use sign convention: u=-20, f=-10 (concave)',formula:'1/v = 1/f - 1/u = 1/(-10) - 1/(-20)\n= -1/10 + 1/20 = -1/20\nv = -20 cm (real, in front)',steps:['u = -20 cm, f = -10 cm (concave)','1/v = 1/f - 1/u','= 1/(-10) - 1/(-20)','= -2/20 + 1/20 = -1/20','v = -20 cm (real image in front of mirror)'],time:18},
sol:'Using mirror formula: 1/v + 1/u = 1/f\nSigns: u = -20 cm, f = -10 cm\n1/v = 1/f - 1/u = -1/10 + 1/20 = -1/20\nv = -20 cm → image is 20 cm in front (real)\n✓ Answer: A'},

{id:'PHY-2021-01',year:2021,subject:'physics',cat:1,diff:'easy',
chapter:'Semiconductors',topic:'p-n Junction',
q:'In a p-n junction diode, the depletion layer:',
opts:{A:'Has no charges',B:'Has mobile charges',C:'Has immobile ions',D:'Is a conductor'},
ans:['C'],
trick:{text:'Depletion layer = fixed/immobile ionized donor and acceptor atoms. Electrons and holes have recombined and left behind fixed charges.',formula:'No mobile carriers in depletion region',steps:['Electrons from n-side recombine with holes from p-side','This leaves behind ionized donors (+) and acceptors (-)','These are fixed crystal atoms — cannot move','∴ Immobile ions only'],time:8},
sol:'The depletion layer is formed when electrons from the n-side diffuse and recombine with holes from the p-side, leaving behind fixed ionized donor atoms (+) on n-side and fixed ionized acceptor atoms (-) on p-side. These ions are part of the crystal lattice and are immobile.\n✓ Answer: C'},

{id:'PHY-2022-01',year:2022,subject:'physics',cat:2,diff:'hard',
chapter:'Current Electricity',topic:'Wheatstone Bridge',
q:'In a Wheatstone bridge P=10Ω, Q=15Ω, R=20Ω. For balance, S should be:',
opts:{A:'30 Ω',B:'25 Ω',C:'15 Ω',D:'20 Ω'},
ans:['A'],
trick:{text:'Balance condition: P/Q = R/S → S = QR/P. Memorize cross multiply!',formula:'P/Q = R/S\n10/15 = 20/S\nS = 20×15/10 = 30Ω',steps:['Bridge balance: P/Q = R/S','S = R×Q/P','= 20×15/10 = 30Ω'],time:10},
sol:'Wheatstone bridge balance: P/Q = R/S\n10/15 = 20/S\nS = (20 × 15)/10 = 30Ω\n✓ Answer: A'},

{id:'PHY-2023-01',year:2023,subject:'physics',cat:1,diff:'medium',
chapter:'Waves',topic:'Doppler Effect',
q:'A source of sound moves towards a stationary observer with velocity vs = 34 m/s. If f₀ = 400 Hz and v_sound = 340 m/s, the observed frequency is:',
opts:{A:'440 Hz',B:'360 Hz',C:'400 Hz',D:'450 Hz'},
ans:['A'],
trick:{text:'Doppler: f = f₀×(v/(v-vs)) when source approaches. Denominator decreases → frequency increases.',formula:'f = f₀ × v/(v-vs)\n= 400 × 340/(340-34)\n= 400 × 340/306 = 400×10/9 ≈ 444... → 440Hz',steps:['Source moving towards observer: f = f₀×v/(v-vs)','= 400 × 340/(340-34)','= 400 × 340/306','= 400 × 1.1... ≈ 440 Hz'],time:18},
sol:'Doppler effect (source approaching):\nf = f₀ × v/(v-vs) = 400 × 340/(340-34) = 400 × 340/306 ≈ 444 Hz → closest is 440 Hz\n✓ Answer: A'},

{id:'PHY-2024-01',year:2024,subject:'physics',cat:1,diff:'medium',
chapter:'Current Electricity',topic:'Terminal Voltage',
q:'A battery of emf 12V and internal resistance 2Ω is connected to an external resistance of 10Ω. The terminal voltage is:',
opts:{A:'10 V',B:'8 V',C:'12 V',D:'6 V'},
ans:['A'],
trick:{text:'V_terminal = ε - Ir = ε × R/(R+r). Voltage divider on external R!',formula:'I = E/(R+r) = 12/12 = 1A\nV = IR = 1×10 = 10V',steps:['I = ε/(R+r) = 12/(10+2) = 1A','Terminal voltage = E - Ir = 12 - 1×2 = 10V','Or: V = IR = 1×10 = 10V'],time:12},
sol:'Current: I = ε/(R+r) = 12/12 = 1A\nTerminal Voltage = ε - Ir = 12 - 1×2 = 10V\nVerification: V = IR = 1×10 = 10V ✓\n✓ Answer: A'},

{id:'PHY-2025-01',year:2025,subject:'physics',cat:2,diff:'hard',
chapter:'Electromagnetic Waves',topic:'EM Spectrum',
q:'Which of the following has the highest frequency?',
opts:{A:'X-rays',B:'UV rays',C:'Gamma rays',D:'Visible light'},
ans:['C'],
trick:{text:'EM spectrum frequency order (low→high): Radio→Micro→IR→Visible→UV→X-ray→Gamma. Gamma always highest!',formula:'f_γ > f_X > f_UV > f_visible',steps:['Remember: "RMIUVXG" (Radio,Micro,IR,UV,X,Gamma)','Frequency increases left to right','Gamma rays have highest frequency','Wavelength is INVERSE of frequency'],time:6},
sol:'Electromagnetic spectrum in increasing frequency:\nRadio < Microwave < IR < Visible < UV < X-rays < Gamma rays\nGamma rays have the highest frequency (~10²⁰ Hz)\n✓ Answer: C'},

// ══════════════════════════════════════════════════════
// MATHEMATICS — 2005–2025
// ══════════════════════════════════════════════════════

{id:'MATH-2005-01',year:2005,subject:'math',cat:1,diff:'easy',
chapter:'Algebra',topic:'AP/GP',
q:'The sum of first n terms of an AP is Sₙ = 3n² + 5n. The 10th term is:',
opts:{A:'62',B:'65',C:'60',D:'63'},
ans:['A'],
trick:{text:'T_n = S_n - S_{n-1}. OR differentiate: T_n = d(Sₙ)/dn at n (for quadratic Sₙ, T_n = 6n-1 after diff, check: T_1=5, S_1=8, T_1=8 ✓ ... use S_n - S_{n-1})',formula:'T₁₀ = S₁₀ - S₉\n= (300+50) - (243+45)\n= 350 - 288 = 62',steps:['T_n = S_n - S_{n-1}','S₁₀ = 3(100)+5(10) = 350','S₉ = 3(81)+5(9) = 288','T₁₀ = 350-288 = 62'],time:10},
sol:'T_n = S_n - S_{n-1}\nS₁₀ = 3(10²)+5(10) = 300+50 = 350\nS₉ = 3(81)+5(9) = 243+45 = 288\nT₁₀ = 350-288 = 62\n✓ Answer: A'},

{id:'MATH-2006-01',year:2006,subject:'math',cat:1,diff:'medium',
chapter:'Trigonometry',topic:'Identities',
q:'The value of sin75° is:',
opts:{A:'(√6+√2)/4',B:'(√6-√2)/4',C:'(√3+1)/4',D:'(√3-1)/4'},
ans:['A'],
trick:{text:'sin75° = sin(45°+30°) = sin45°cos30° + cos45°sin30°',formula:'= (1/√2)(√3/2) + (1/√2)(1/2)\n= (√3+1)/(2√2) = (√6+√2)/4',steps:['sin75° = sin(45+30)','= sin45°cos30° + cos45°sin30°','= (√2/2)(√3/2) + (√2/2)(1/2)','= (√6/4) + (√2/4) = (√6+√2)/4'],time:15},
sol:'sin75° = sin(45+30)\n= sin45°cos30° + cos45°sin30°\n= (√2/2)(√3/2) + (√2/2)(1/2)\n= √6/4 + √2/4 = (√6+√2)/4\n✓ Answer: A'},

{id:'MATH-2007-01',year:2007,subject:'math',cat:1,diff:'medium',
chapter:'Calculus',topic:'Differentiation',
q:'If y = x³ + 3x² - 5x + 2, then dy/dx at x=1 is:',
opts:{A:'4',B:'6',C:'2',D:'8'},
ans:['A'],
trick:{text:'Differentiate term by term, then substitute x=1.',formula:'dy/dx = 3x²+6x-5\nAt x=1: 3+6-5 = 4',steps:['dy/dx = 3x² + 6x - 5','At x=1: = 3(1)+6(1)-5','= 3+6-5 = 4'],time:8},
sol:'y = x³+3x²-5x+2\ndy/dx = 3x²+6x-5\nAt x=1: dy/dx = 3+6-5 = 4\n✓ Answer: A'},

{id:'MATH-2008-01',year:2008,subject:'math',cat:1,diff:'hard',
chapter:'Coordinate Geometry',topic:'Circles',
q:'The equation of circle with centre (2,-3) and radius 5 is:',
opts:{A:'x²+y²-4x+6y-12=0',B:'x²+y²+4x-6y-12=0',C:'x²+y²-4x-6y-12=0',D:'x²+y²+4x+6y-12=0'},
ans:['A'],
trick:{text:'Standard: (x-h)²+(y-k)²=r². Expand and check sign of h,k terms.',formula:'(x-2)²+(y+3)²=25\nx²-4x+4+y²+6y+9=25\nx²+y²-4x+6y-12=0',steps:['Center (2,-3), radius 5','(x-2)²+(y+3)²=25','x²-4x+4+y²+6y+9=25','x²+y²-4x+6y+13-25=0','x²+y²-4x+6y-12=0 ✓'],time:18},
sol:'(x-2)²+(y-(-3))²=5²\n(x-2)²+(y+3)²=25\nx²-4x+4+y²+6y+9=25\nx²+y²-4x+6y-12=0\n✓ Answer: A'},

{id:'MATH-2009-01',year:2009,subject:'math',cat:2,diff:'hard',
chapter:'Calculus',topic:'Integration',
q:'∫₀¹ x·eˣ dx = ?',
opts:{A:'1',B:'e-1',C:'e',D:'e+1'},
ans:['A'],
trick:{text:'Integration by Parts: ∫u·dv = uv - ∫v·du. Take u=x, dv=eˣdx',formula:'= [x·eˣ]₀¹ - ∫₀¹ eˣ dx\n= (e-0) - [eˣ]₀¹\n= e - (e-1) = 1',steps:['u=x → du=dx; dv=eˣdx → v=eˣ','∫x·eˣdx = x·eˣ - ∫eˣdx','= x·eˣ - eˣ','From 0 to 1: (e-e)-(0-1) = 0+1 = 1'],time:20},
sol:'Using IBP: u=x, dv=eˣdx\n∫₀¹ xeˣdx = [xeˣ]₀¹ - ∫₀¹ eˣdx\n= (1·e¹ - 0) - [eˣ]₀¹\n= e - (e-1) = e - e + 1 = 1\n✓ Answer: A'},

{id:'MATH-2010-01',year:2010,subject:'math',cat:1,diff:'medium',
chapter:'Algebra',topic:'Complex Numbers',
q:'The modulus of (3+4i) is:',
opts:{A:'5',B:'7',C:'25',D:'√7'},
ans:['A'],
trick:{text:'|a+bi| = √(a²+b²). Classic 3-4-5 Pythagorean triple!',formula:'|3+4i| = √(9+16) = √25 = 5',steps:['|a+bi| = √(a²+b²)','= √(3²+4²) = √(9+16)','= √25 = 5 (3-4-5 triple!)'],time:5},
sol:'Modulus of complex number z = a+bi is |z| = √(a²+b²)\n|3+4i| = √(3²+4²) = √(9+16) = √25 = 5\n✓ Answer: A'},

{id:'MATH-2011-01',year:2011,subject:'math',cat:1,diff:'medium',
chapter:'Calculus',topic:'Limits',
q:'lim(x→0) (sinx)/x = ?',
opts:{A:'0',B:'1',C:'∞',D:'1/2'},
ans:['B'],
trick:{text:'Standard result: lim(x→0) sinx/x = 1. MEMORIZE this!',formula:'lim(x→0) sinx/x = 1',steps:['This is a standard fundamental limit','Proof via L\'Hopital: d/dx(sinx)/d/dx(x) = cosx/1','At x=0: cos0 = 1','∴ limit = 1'],time:4},
sol:'Standard limit: lim(x→0) sinx/x = 1\nThis is a fundamental result. Can be verified by L\'Hopital\'s rule:\nd(sinx)/dx = cosx; d(x)/dx = 1\nLimit = cos0/1 = 1\n✓ Answer: B'},

{id:'MATH-2012-01',year:2012,subject:'math',cat:1,diff:'hard',
chapter:'Calculus',topic:'Maxima & Minima',
q:'The function f(x) = x³ - 3x has local minimum at x = ?',
opts:{A:'x=1',B:'x=-1',C:'x=0',D:'x=√3'},
ans:['A'],
trick:{text:'f\'(x)=0 for critical points, then f\'\'(x)>0 for minimum.',formula:'f\'(x) = 3x²-3 = 0 → x=±1\nf\'\'(x) = 6x\nAt x=1: f\'\'=6>0 → minimum',steps:['f\'(x) = 3x²-3','3x²-3=0 → x²=1 → x=±1','f\'\'(x) = 6x','f\'\'(1) = 6 > 0 → local minimum at x=1','f\'\'(-1) = -6 < 0 → local maximum at x=-1'],time:18},
sol:'f\'(x) = 3x²-3 = 0 → x = ±1\nf\'\'(x) = 6x\nAt x=1: f\'\'(1) = 6 > 0 → local minimum\nAt x=-1: f\'\'(-1) = -6 < 0 → local maximum\n✓ Answer: A'},

{id:'MATH-2013-01',year:2013,subject:'math',cat:1,diff:'medium',
chapter:'Vectors',topic:'Dot Product',
q:'If vectors A = 2î + 3ĵ and B = 4î - ĵ, then A·B is:',
opts:{A:'5',B:'8',C:'11',D:'2'},
ans:['A'],
trick:{text:'A·B = (2)(4)+(3)(-1) = 8-3 = 5. Component-wise multiply and add!',formula:'A·B = AxBx + AyBy + AzBz',steps:['A = 2î+3ĵ, B = 4î-ĵ','A·B = (2)(4) + (3)(-1)','= 8 - 3 = 5'],time:8},
sol:'A·B = (2)(4) + (3)(-1) = 8 - 3 = 5\n✓ Answer: A'},

{id:'MATH-2014-01',year:2014,subject:'math',cat:1,diff:'hard',
chapter:'Algebra',topic:'Matrices',
q:'If A = [[1,2],[3,4]], then det(A) is:',
opts:{A:'-2',B:'2',C:'-10',D:'10'},
ans:['A'],
trick:{text:'det [[a,b],[c,d]] = ad - bc. Cross multiply: diagonal down minus diagonal up.',formula:'det = (1)(4)-(2)(3) = 4-6 = -2',steps:['det [[a,b],[c,d]] = ad-bc','= 1×4 - 2×3','= 4 - 6 = -2'],time:6},
sol:'det(A) = (1)(4) - (2)(3) = 4 - 6 = -2\n✓ Answer: A'},

{id:'MATH-2015-01',year:2015,subject:'math',cat:2,diff:'hard',
chapter:'Probability',topic:'Conditional Probability',
q:'Two dice are thrown simultaneously. The probability that sum is 7 is:',
opts:{A:'1/6',B:'1/12',C:'7/36',D:'5/36'},
ans:['A'],
trick:{text:'Pairs summing to 7: (1,6)(2,5)(3,4)(4,3)(5,2)(6,1) = 6 pairs. Total = 36.',formula:'P(sum=7) = 6/36 = 1/6',steps:['Total outcomes = 6×6 = 36','Favorable: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6','P = 6/36 = 1/6'],time:12},
sol:'Total outcomes = 36\nFavorable outcomes (sum=7): (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6\nP(sum=7) = 6/36 = 1/6\n✓ Answer: A'},

{id:'MATH-2016-01',year:2016,subject:'math',cat:1,diff:'medium',
chapter:'Coordinate Geometry',topic:'Straight Lines',
q:'The slope of line joining (2,3) and (5,9) is:',
opts:{A:'2',B:'3',C:'4',D:'1'},
ans:['A'],
trick:{text:'Slope m = (y₂-y₁)/(x₂-x₁). Just difference of y over difference of x.',formula:'m = (9-3)/(5-2) = 6/3 = 2',steps:['m = (y₂-y₁)/(x₂-x₁)','= (9-3)/(5-2)','= 6/3 = 2'],time:6},
sol:'Slope m = (y₂-y₁)/(x₂-x₁) = (9-3)/(5-2) = 6/3 = 2\n✓ Answer: A'},

{id:'MATH-2017-01',year:2017,subject:'math',cat:3,diff:'hard',
chapter:'Calculus',topic:'Definite Integration',
q:'∫₀^π sin x dx = ?',
opts:{A:'0',B:'2',C:'-2',D:'1'},
ans:['B'],
trick:{text:'∫sinx dx = -cosx. From 0 to π: -cosπ-(-cos0) = -(-1)+1 = 2.',formula:'[-cosx]₀^π = -cosπ+cos0 = 1+1 = 2',steps:['∫sinx dx = -cosx + C','Apply limits 0 to π:','= [-cosx]₀^π','= (-cosπ)-(-cos0)','= -(-1)+1 = 1+1 = 2'],time:10},
sol:'∫₀^π sinx dx = [-cosx]₀^π\n= (-cosπ) - (-cos0)\n= -(-1) - (-1)\n= 1 + 1 = 2\n✓ Answer: B'},

{id:'MATH-2018-01',year:2018,subject:'math',cat:1,diff:'medium',
chapter:'Algebra',topic:'Binomial Theorem',
q:'The number of terms in the expansion of (a+b)¹⁰ is:',
opts:{A:'10',B:'11',C:'9',D:'12'},
ans:['B'],
trick:{text:'(a+b)ⁿ has (n+1) terms. Just add 1 to the power!',formula:'Terms = n+1 = 10+1 = 11',steps:['(a+b)ⁿ has (n+1) terms','n=10 → terms = 11'],time:5},
sol:'The expansion of (a+b)ⁿ has (n+1) terms\nFor n=10: number of terms = 11\n✓ Answer: B'},

{id:'MATH-2019-01',year:2019,subject:'math',cat:2,diff:'hard',
chapter:'Calculus',topic:'Differential Equations',
q:'Solution of dy/dx = y/x is:',
opts:{A:'y=cx',B:'y=x+c',C:'xy=c',D:'y=x²+c'},
ans:['A'],
trick:{text:'Separate variables: dy/y = dx/x → lny = lnx + lnc → y=cx. Standard separable DE!',formula:'dy/y = dx/x\n∫dy/y = ∫dx/x\nlny = lnx + C\ny = cx',steps:['dy/dx = y/x','dy/y = dx/x (separate variables)','Integrate both sides','lny = lnx + lnc','y = cx'],time:15},
sol:'dy/dx = y/x → dy/y = dx/x\n∫dy/y = ∫dx/x\nln|y| = ln|x| + ln|c|\ny = cx\n✓ Answer: A'},

{id:'MATH-2020-01',year:2020,subject:'math',cat:1,diff:'medium',
chapter:'Algebra',topic:'Permutations',
q:'In how many ways can 5 books be arranged on a shelf?',
opts:{A:'120',B:'60',C:'24',D:'25'},
ans:['A'],
trick:{text:'5 books in 5 positions: 5! = 5×4×3×2×1 = 120. FACTORIAL!',formula:'5! = 120',steps:['n distinct objects in n positions = n!','5! = 5×4×3×2×1','= 20×6 = 120'],time:6},
sol:'5 books arranged in 5 positions = 5!\n= 5×4×3×2×1 = 120\n✓ Answer: A'},

{id:'MATH-2021-01',year:2021,subject:'math',cat:1,diff:'hard',
chapter:'Calculus',topic:'Area under Curve',
q:'Area bounded by y=x², x=0, x=3, and x-axis is:',
opts:{A:'9',B:'27',C:'3',D:'18'},
ans:['A'],
trick:{text:'Area = ∫₀³ x² dx = [x³/3]₀³ = 27/3 = 9.',formula:'∫₀³ x² dx = [x³/3]₀³ = 9',steps:['Area = ∫₀³ x² dx','= [x³/3] from 0 to 3','= 27/3 - 0','= 9 sq units'],time:10},
sol:'Area = ∫₀³ x² dx = [x³/3]₀³ = (27/3) - 0 = 9\n✓ Answer: A'},

{id:'MATH-2022-01',year:2022,subject:'math',cat:2,diff:'hard',
chapter:'Algebra',topic:'Sequences & Series',
q:'If the 3rd and 7th terms of an AP are 4 and 12, the common difference is:',
opts:{A:'2',B:'3',C:'1',D:'4'},
ans:['A'],
trick:{text:'T₇ - T₃ = (7-3)d = 4d. So d = (12-4)/4 = 2. Gap trick!',formula:'T_n = a+(n-1)d\nT₇-T₃ = 4d = 8\nd = 2',steps:['T₃ = a+2d = 4','T₇ = a+6d = 12','Subtract: 4d = 8','d = 2'],time:10},
sol:'T₃ = a+2d = 4\nT₇ = a+6d = 12\nSubtracting: (a+6d)-(a+2d) = 12-4\n4d = 8 → d = 2\n✓ Answer: A'},

{id:'MATH-2023-01',year:2023,subject:'math',cat:1,diff:'medium',
chapter:'Trigonometry',topic:'Inverse Trig',
q:'The value of sin⁻¹(1) is:',
opts:{A:'π/2',B:'π',C:'0',D:'π/4'},
ans:['A'],
trick:{text:'sin(π/2)=1. Therefore sin⁻¹(1)=π/2. Principal range of sin⁻¹ is [-π/2, π/2].',formula:'sin⁻¹(1) = π/2 ≈ 90°',steps:['sin(90°) = sin(π/2) = 1','sin⁻¹(1) = π/2','Principal value range: [-π/2, π/2]'],time:5},
sol:'Since sin(π/2) = 1, sin⁻¹(1) = π/2\nPrincipal value range of sin⁻¹ is [-π/2, π/2]\n✓ Answer: A'},

{id:'MATH-2024-01',year:2024,subject:'math',cat:1,diff:'hard',
chapter:'Calculus',topic:'Integration by Substitution',
q:'∫ 2x/(x²+1) dx = ?',
opts:{A:'ln(x²+1)+C',B:'2ln(x²+1)+C',C:'ln(2x)+C',D:'1/(x²+1)+C'},
ans:['A'],
trick:{text:'Numerator is derivative of denominator! ∫f\'(x)/f(x)dx = ln|f(x)|+C',formula:'Let u=x²+1, du=2x dx\n∫du/u = ln|u|+C = ln(x²+1)+C',steps:['Let u = x²+1','du = 2x dx','∫2x/(x²+1)dx = ∫du/u','= ln|u|+C = ln(x²+1)+C'],time:12},
sol:'Substitution: let u = x²+1, then du = 2x dx\n∫2x/(x²+1)dx = ∫du/u = ln|u|+C = ln(x²+1)+C\n✓ Answer: A'},

{id:'MATH-2025-01',year:2025,subject:'math',cat:2,diff:'hard',
chapter:'Algebra',topic:'Quadratic Equations',
q:'If α and β are roots of x²-5x+6=0, then α²+β² is:',
opts:{A:'13',B:'25',C:'12',D:'36'},
ans:['A'],
trick:{text:'α+β = -(-5)/1 = 5, αβ = 6/1 = 6. Then α²+β² = (α+β)²-2αβ = 25-12=13',formula:'α²+β² = (α+β)²-2αβ = 25-12 = 13',steps:['By Vieta: α+β = 5, αβ = 6','α²+β² = (α+β)²-2αβ','= 25 - 2×6','= 25 - 12 = 13'],time:12},
sol:'By Vieta\'s formulas: α+β = 5, αβ = 6\nα²+β² = (α+β)² - 2αβ = 25 - 12 = 13\n✓ Answer: A'},

// ══════════════════════════════════════════════════════
// CHEMISTRY — 2005–2025
// ══════════════════════════════════════════════════════

{id:'CHEM-2005-01',year:2005,subject:'chemistry',cat:1,diff:'easy',
chapter:'Atomic Structure',topic:'Quantum Numbers',
q:'The maximum number of electrons in a shell with n=3 is:',
opts:{A:'18',B:'8',C:'32',D:'2'},
ans:['A'],
trick:{text:'Max electrons in shell n = 2n². For n=3: 2×9 = 18.',formula:'Max e⁻ = 2n²\nn=3: 2×9 = 18',steps:['Formula: 2n² electrons per shell','n=3: 2×3² = 2×9 = 18','Shells: K(2), L(8), M(18), N(32)'],time:5},
sol:'Maximum electrons in nth shell = 2n²\nFor n=3 (M shell): 2×3² = 18\n✓ Answer: A'},

{id:'CHEM-2006-01',year:2006,subject:'chemistry',cat:1,diff:'medium',
chapter:'Chemical Bonding',topic:'Hybridisation',
q:'The hybridisation of SF₆ is:',
opts:{A:'sp³d',B:'sp³',C:'sp³d²',D:'sp²'},
ans:['C'],
trick:{text:'H = ½(V+X-C+A). S: V=6, F: X=6, charge=0. H=½(6+6)=6 → sp³d²',formula:'H = ½(V+X) = ½(6+6) = 6\n6 pairs → sp³d²',steps:['S has 6 valence electrons','6 F atoms bond → 6 electron pairs total','6 pairs = sp³d² hybridisation','Octahedral geometry'],time:10},
sol:'S in SF₆: 6 valence e⁻, 6 bond pairs with F atoms\nTotal = 6 electron pairs → sp³d² hybridisation\nShape: Regular octahedral\n✓ Answer: C'},

{id:'CHEM-2007-01',year:2007,subject:'chemistry',cat:1,diff:'easy',
chapter:'Chemical Equilibrium',topic:'Le Chatelier Principle',
q:'For N₂+3H₂⇌2NH₃ (ΔH<0), increasing temperature will:',
opts:{A:'Increase NH₃',B:'Decrease NH₃',C:'No change',D:'Increase N₂ and H₂ only'},
ans:['B'],
trick:{text:'Exothermic reaction (ΔH<0). Increase T → equilibrium shifts LEFT (backward). Le Chatelier!',formula:'Heat is product in exothermic rxn\nMore heat → backward shift → less NH₃',steps:['ΔH<0 means exothermic','Treat heat as a product','Increase T = adding heat','Equilibrium shifts left (backward)','NH₃ decreases'],time:8},
sol:'The reaction is exothermic (ΔH<0). Treat heat as a product:\nN₂+3H₂ ⇌ 2NH₃ + heat\nIncreasing temperature → equilibrium shifts backward\n→ NH₃ decreases\n✓ Answer: B'},

{id:'CHEM-2008-01',year:2008,subject:'chemistry',cat:1,diff:'medium',
chapter:'Thermodynamics',topic:'Gibbs Energy',
q:'For a spontaneous process at constant T and P, ΔG should be:',
opts:{A:'Positive',B:'Zero',C:'Negative',D:'Any value'},
ans:['C'],
trick:{text:'ΔG < 0 → spontaneous. ΔG = 0 → equilibrium. ΔG > 0 → non-spontaneous. MEMORIZE!',formula:'ΔG = ΔH - TΔS\nSpontaneous: ΔG < 0',steps:['ΔG < 0: spontaneous (releases free energy)','ΔG = 0: system at equilibrium','ΔG > 0: non-spontaneous','For any spontaneous process: ΔG < 0'],time:6},
sol:'Gibbs free energy criterion:\nΔG < 0 → process is spontaneous\nΔG = 0 → equilibrium\nΔG > 0 → non-spontaneous\nFor spontaneous process: ΔG must be negative\n✓ Answer: C'},

{id:'CHEM-2009-01',year:2009,subject:'chemistry',cat:1,diff:'hard',
chapter:'Electrochemistry',topic:'Nernst Equation',
q:'For the cell Zn|Zn²⁺||Cu²⁺|Cu, E°cell = 1.1V. At 25°C, the Nernst equation gives:',
opts:{A:'E=1.1-0.059/2×log([Zn²⁺]/[Cu²⁺])',B:'E=1.1+0.059/2×log([Cu²⁺]/[Zn²⁺])',C:'E=1.1-0.059/2×log([Cu²⁺]/[Zn²⁺])',D:'E=1.1-0.059×log([Zn²⁺]/[Cu²⁺])'},
ans:['A'],
trick:{text:'Nernst: E = E° - (0.0592/n)×logQ. Here n=2, Q=[Zn²⁺]/[Cu²⁺]',formula:'E = E° - 0.0592/n × log Q\nQ = [products]/[reactants] = [Zn²⁺]/[Cu²⁺]',steps:['Reaction: Zn+Cu²⁺→Zn²⁺+Cu','n=2 electrons transferred','Q=[Zn²⁺]/[Cu²⁺] (products/reactants)','E=1.1-(0.059/2)log([Zn²⁺]/[Cu²⁺])'],time:20},
sol:'Nernst equation: E = E° - (RT/nF)lnQ = E° - (0.0592/n)logQ at 25°C\nCell: Zn+Cu²⁺→Zn²⁺+Cu, n=2\nQ = [Zn²⁺]/[Cu²⁺]\nE = 1.1 - (0.059/2)×log([Zn²⁺]/[Cu²⁺])\n✓ Answer: A'},

{id:'CHEM-2010-01',year:2010,subject:'chemistry',cat:1,diff:'medium',
chapter:'Organic Chemistry',topic:'IUPAC Nomenclature',
q:'The IUPAC name of CH₃-CH(OH)-CH₃ is:',
opts:{A:'2-propanol',B:'1-propanol',C:'propan-2-ol',D:'isopropanol'},
ans:['C'],
trick:{text:'Number from end nearest to OH. OH is at C2. Name: propan-2-ol (modern IUPAC places locant before functional group suffix).',formula:'propan-2-ol (IUPAC 2013)',steps:['3 C chain: propan-','OH at middle carbon = C2','-2-ol suffix','IUPAC: propan-2-ol'],time:8},
sol:'Chain: 3 carbons → propane\nOH at position 2 → prop-2-ol\nFull IUPAC name: propan-2-ol\n✓ Answer: C'},

{id:'CHEM-2011-01',year:2011,subject:'chemistry',cat:1,diff:'easy',
chapter:'Periodic Table',topic:'Periodic Trends',
q:'Which has the smallest atomic radius in Period 2?',
opts:{A:'Li',B:'Be',C:'Ne',D:'F'},
ans:['C'],
trick:{text:'Atomic radius decreases across a period (left to right). Ne is last in Period 2 → smallest radius. But wait — noble gases have unusual definition. F is smallest among regular elements, but Ne is technically smallest!',formula:'Radius order: Li>Be>B>C>N>O>F>Ne',steps:['Period 2: Li to Ne','Z increases → more nuclear charge','More charge → electrons pulled closer','Radius decreases across period','Ne at end → smallest radius'],time:8},
sol:'Across a period, atomic radius decreases due to increasing nuclear charge with same principal quantum number.\nPeriod 2: Li(152pm) > Be > B > C > N > O > F > Ne(smallest)\n✓ Answer: C'},

{id:'CHEM-2012-01',year:2012,subject:'chemistry',cat:1,diff:'medium',
chapter:'Solutions',topic:'Colligative Properties',
q:'Which colligative property is used to determine molecular mass of a polymer?',
opts:{A:'Elevation of boiling point',B:'Depression of freezing point',C:'Osmotic pressure',D:'Lowering of vapour pressure'},
ans:['C'],
trick:{text:'Osmotic pressure (π=CRT) gives larger, measurable values even for dilute polymer solutions. Best for very high molecular masses!',formula:'π = CRT = nRT/V\nHigh M → very low conc needed',steps:['Polymers have very high molecular mass','Very low molality → tiny boiling pt elevation','Osmotic pressure: π=MRT is most sensitive','Even dilute solutions give measurable π','∴ Osmotic pressure preferred'],time:10},
sol:'For polymers (very high M), other colligative properties give very small values.\nOsmotic pressure (π=CRT) is most sensitive and gives measurable values even for very dilute solutions.\n✓ Answer: C'},

{id:'CHEM-2013-01',year:2013,subject:'chemistry',cat:2,diff:'hard',
chapter:'Reaction Kinetics',topic:'Rate Law',
q:'For a first-order reaction, the half-life is 693 seconds. The rate constant k is:',
opts:{A:'10⁻³ s⁻¹',B:'10⁻² s⁻¹',C:'10⁻⁴ s⁻¹',D:'693 s⁻¹'},
ans:['A'],
trick:{text:'t₁/₂ = 0.693/k for 1st order. So k = 0.693/t₁/₂',formula:'k = 0.693/t₁/₂ = 0.693/693 = 10⁻³ s⁻¹',steps:['1st order: t₁/₂ = 0.693/k','k = 0.693/t₁/₂','= 0.693/693 = 0.001','= 10⁻³ s⁻¹'],time:10},
sol:'For 1st order reaction: t₁/₂ = 0.693/k\nk = 0.693/t₁/₂ = 0.693/693 = 10⁻³ s⁻¹\n✓ Answer: A'},

{id:'CHEM-2014-01',year:2014,subject:'chemistry',cat:1,diff:'medium',
chapter:'s-Block Elements',topic:'Properties of Group 1',
q:'Which alkali metal has the highest ionization energy?',
opts:{A:'Li',B:'Na',C:'K',D:'Cs'},
ans:['A'],
trick:{text:'IE decreases down a group (larger atom = easier to remove e⁻). Smallest atom Li → highest IE.',formula:'IE: Li>Na>K>Rb>Cs',steps:['IE decreases down group 1','Li is at top → smallest size','Smallest atom → electrons held tightest','Li has highest IE in group 1'],time:6},
sol:'Ionization energy decreases as we go down Group 1 (alkali metals) because atomic size increases and nuclear charge effect decreases. Li has the smallest size → highest IE.\n✓ Answer: A'},

{id:'CHEM-2015-01',year:2015,subject:'chemistry',cat:1,diff:'hard',
chapter:'Coordination Chemistry',topic:'VSEPR & Geometry',
q:'The geometry of [Ni(CO)₄] is:',
opts:{A:'Square planar',B:'Tetrahedral',C:'Octahedral',D:'Trigonal planar'},
ans:['B'],
trick:{text:'Ni(CO)₄: CO is strong field, Ni(0) d¹⁰. With 4 CO ligands and d¹⁰: Tetrahedral!',formula:'Ni(0) = d¹⁰, 4 CO ligands → tetrahedral',steps:['Ni(0): [Ar]3d¹⁰4s⁰ (all d filled)','CO is strong field ligand','4 ligands + d¹⁰ → tetrahedral','(Square planar only for d⁸ 4-coordinate)'],time:12},
sol:'In [Ni(CO)₄]:\n- Ni has oxidation state 0 → d¹⁰ configuration\n- 4 CO ligands → 4-coordinate\n- d¹⁰ does not force square planar\n- Geometry: Tetrahedral\n✓ Answer: B'},

{id:'CHEM-2016-01',year:2016,subject:'chemistry',cat:1,diff:'medium',
chapter:'Organic Chemistry',topic:'Reactions',
q:'Which reagent converts an aldehyde to primary alcohol?',
opts:{A:'NaBH₄',B:'K₂Cr₂O₇/H⁺',C:'KMnO₄',D:'PCC'},
ans:['A'],
trick:{text:'NaBH₄ (sodium borohydride) = mild reducing agent. Reduces C=O to C-OH. Aldehyde → 1° alcohol.',formula:'RCHO + NaBH₄ → RCH₂OH\nC=O reduction',steps:['NaBH₄ = reducing agent (provides H⁻)','Attacks electrophilic C=O','Aldehyde → primary alcohol','K₂Cr₂O₇ = oxidizing agent (wrong direction)'],time:8},
sol:'NaBH₄ (sodium borohydride) is a reducing agent that converts:\nAldehyde (RCHO) → Primary alcohol (RCH₂OH)\nK₂Cr₂O₇ and KMnO₄ are oxidizing agents (opposite direction)\n✓ Answer: A'},

{id:'CHEM-2017-01',year:2017,subject:'chemistry',cat:1,diff:'easy',
chapter:'Mole Concept',topic:'Avogadro\'s Number',
q:'How many molecules are present in 18g of H₂O?',
opts:{A:'6.022×10²³',B:'12.044×10²³',C:'3.011×10²³',D:'1.806×10²⁴'},
ans:['A'],
trick:{text:'Molar mass of H₂O = 18 g/mol. 18g = 1 mole = 6.022×10²³ molecules.',formula:'18g H₂O = 1 mol\n= 6.022×10²³ molecules',steps:['M(H₂O) = 2(1)+16 = 18 g/mol','18g/18g·mol⁻¹ = 1 mol','1 mol = Avogadro\'s number = 6.022×10²³'],time:5},
sol:'Molar mass of H₂O = 18 g/mol\nMoles = 18/18 = 1 mol\nMolecules = 1 × 6.022×10²³ = 6.022×10²³\n✓ Answer: A'},

{id:'CHEM-2018-01',year:2018,subject:'chemistry',cat:1,diff:'medium',
chapter:'p-Block Elements',topic:'Oxides',
q:'Which is an amphoteric oxide?',
opts:{A:'Na₂O',B:'Al₂O₃',C:'SO₃',D:'P₄O₁₀'},
ans:['B'],
trick:{text:'Amphoteric = reacts with BOTH acid AND base. Al₂O₃ is the classic example. Al is a metalloid-like element.',formula:'Al₂O₃+H₂SO₄→Al₂(SO₄)₃+H₂O (acid)\nAl₂O₃+NaOH→NaAlO₂+H₂O (base)',steps:['Na₂O = basic oxide','SO₃ = acidic oxide','Al₂O₃ = amphoteric (reacts both)','Al₂O₃+H₂SO₄→salt+water (acidic side)','Al₂O₃+NaOH→NaAlO₂+H₂O (basic side)'],time:8},
sol:'Amphoteric oxides react with both acids and bases:\nAl₂O₃+3H₂SO₄→Al₂(SO₄)₃+3H₂O (acts as base)\nAl₂O₃+2NaOH→2NaAlO₂+H₂O (acts as acid)\nOther amphoteric oxides: ZnO, SnO, PbO\n✓ Answer: B'},

{id:'CHEM-2019-01',year:2019,subject:'chemistry',cat:2,diff:'hard',
chapter:'Organic Chemistry',topic:'Aromatic Compounds',
q:'Benzene undergoes electrophilic substitution rather than addition because:',
opts:{A:'Benzene is unstable',B:'Addition would destroy aromaticity',C:'Benzene has no π bonds',D:'Electrophiles attack σ bonds'},
ans:['B'],
trick:{text:'Benzene\'s stability comes from aromatic delocalization (resonance energy ~150 kJ/mol). Addition destroys this → thermodynamically unfavorable!',formula:'Addition → lose aromaticity\nSubstitution → restore aromaticity',steps:['Benzene has special stability: 6π electrons delocalized','Hückel rule: 4n+2=6, n=1 → aromatic','Addition product: cyclohexadiene (less stable)','Substitution: aromatic ring restored','∴ Substitution preferred energetically'],time:12},
sol:'Benzene has special aromatic stability (extra ~150 kJ/mol of resonance energy) due to cyclic conjugation of 6π electrons (Hückel rule: 4n+2, n=1).\nAddition would destroy this delocalization → thermodynamically unfavorable.\nElectrophilic substitution restores aromaticity → preferred.\n✓ Answer: B'},

{id:'CHEM-2020-01',year:2020,subject:'chemistry',cat:1,diff:'medium',
chapter:'Chemical Bonding',topic:'VSEPR',
q:'The shape of water molecule (H₂O) is:',
opts:{A:'Linear',B:'Bent/V-shaped',C:'Tetrahedral',D:'Trigonal planar'},
ans:['B'],
trick:{text:'O: 6 valence e⁻. 2 bond pairs + 2 lone pairs = 4 pairs = sp³. 2 lone pairs → bent shape.',formula:'O: 2 bond pairs + 2 lone pairs\nsp³ → bent (V-shaped)',steps:['O has 6 valence electrons','2 H atoms bond → 2 bond pairs','Remaining = 2 lone pairs','4 total pairs → sp³ (tetrahedral arrangement)','2 lone pairs → push bonds → BENT shape'],time:8},
sol:'H₂O: O has 2 bond pairs (with 2H) + 2 lone pairs\nElectron geometry: tetrahedral (sp³)\nMolecular shape: bent/V-shaped (lone pairs not counted in shape)\nBond angle: ~104.5°\n✓ Answer: B'},

{id:'CHEM-2021-01',year:2021,subject:'chemistry',cat:1,diff:'hard',
chapter:'Electrochemistry',topic:'Electrolysis',
q:'The charge required to deposit 1 mole of Al from Al³⁺ solution is:',
opts:{A:'96500 C',B:'3×96500 C',C:'96500/3 C',D:'2×96500 C'},
ans:['B'],
trick:{text:'Al³⁺ + 3e⁻ → Al. 3 electrons per atom. 1 Faraday = 96500C per mole of e⁻. So 3F needed!',formula:'Al³⁺+3e⁻→Al\nCharge = n×F = 3×96500 C',steps:['Al³⁺ needs 3e⁻ per ion to reduce','1 mole Al needs 3 mole electrons','1 mole e⁻ = 1 Faraday = 96500 C','Charge = 3F = 3×96500 C'],time:10},
sol:'Al³⁺ + 3e⁻ → Al (3 electrons needed per Al atom)\nTo deposit 1 mole of Al: 3 moles of electrons needed\nCharge = 3 × Faraday = 3 × 96500 = 289500 C = 3F\n✓ Answer: B'},

{id:'CHEM-2022-01',year:2022,subject:'chemistry',cat:1,diff:'easy',
chapter:'Organic Chemistry',topic:'Polymers',
q:'Nylon-6,6 is formed from:',
opts:{A:'Adipic acid + hexamethylene diamine',B:'Caprolactam',C:'Styrene',D:'Vinyl chloride'},
ans:['A'],
trick:{text:'Nylon-6,6: 6 carbons in acid + 6 carbons in amine = 6,6. Nylon-6 comes from caprolactam (1 monomer).',formula:'HOOC-(CH₂)₄-COOH + H₂N-(CH₂)₆-NH₂\nAdipic acid + Hexamethylene diamine',steps:['Nylon-6,6: condensation polymer','Two monomers: diacid + diamine','Adipic acid: 6C dicarboxylic acid','Hexamethylene diamine: 6C diamine','Forms amide bonds → nylon'],time:8},
sol:'Nylon-6,6 is a polyamide formed by condensation polymerization of:\n- Adipic acid (hexanedioic acid, 6C)\n- Hexamethylene diamine (1,6-diaminohexane, 6C)\nThe "6,6" refers to 6 carbons in each monomer.\n✓ Answer: A'},

{id:'CHEM-2023-01',year:2023,subject:'chemistry',cat:1,diff:'medium',
chapter:'Chemical Kinetics',topic:'Activation Energy',
q:'According to Arrhenius equation, increasing temperature increases rate constant because:',
opts:{A:'Frequency factor A decreases',B:'More molecules exceed activation energy Ea',C:'Activation energy decreases',D:'Equilibrium constant changes'},
ans:['B'],
trick:{text:'k = Ae^(-Ea/RT). Higher T → larger fraction of molecules have energy ≥ Ea → more effective collisions.',formula:'k = A·e^(-Ea/RT)\nHigher T → e^(-Ea/RT) increases',steps:['Arrhenius: k = Ae^(-Ea/RT)','Higher T → -Ea/RT becomes less negative','e^(-Ea/RT) increases','More molecules have E ≥ Ea','Rate increases'],time:10},
sol:'From Arrhenius equation: k = Ae^(-Ea/RT)\nAs T increases, the exponential factor e^(-Ea/RT) increases.\nThis means more molecules have kinetic energy ≥ activation energy Ea.\nMore effective collisions → higher rate constant k.\n✓ Answer: B'},

{id:'CHEM-2024-01',year:2024,subject:'chemistry',cat:2,diff:'hard',
chapter:'Organic Chemistry',topic:'Named Reactions',
q:'Aldol condensation between two molecules of acetaldehyde gives:',
opts:{A:'Acetone',B:'3-hydroxybutanal',C:'Crotonaldehyde after dehydration',D:'Both B and C'},
ans:['D'],
trick:{text:'Aldol: α-carbon attacks carbonyl → β-hydroxy aldehyde (aldol). Then dehydration → α,β-unsaturated aldehyde (crotonaldehyde).',formula:'2CH₃CHO →[OH⁻]→ CH₃CH(OH)CH₂CHO (aldol)\n→[-H₂O]→ CH₃CH=CHCHO (crotonaldehyde)',steps:['Step 1: Enolate of CH₃CHO formed','Step 2: Attacks another CH₃CHO','Gives 3-hydroxybutanal (B)','Step 3: Dehydration → crotonaldehyde (C)','Both B and C are correct → D'],time:15},
sol:'Aldol condensation of 2 CH₃CHO:\n1) Aldol product: 3-hydroxybutanal [CH₃CH(OH)CH₂CHO]\n2) Aldol condensation (with dehydration): Crotonaldehyde [CH₃CH=CHCHO]\nBoth products are formed depending on conditions.\n✓ Answer: D'},

{id:'CHEM-2025-01',year:2025,subject:'chemistry',cat:1,diff:'medium',
chapter:'Environmental Chemistry',topic:'Air Pollution',
q:'The main cause of photochemical smog is:',
opts:{A:'SO₂',B:'CO',C:'NO₂ and hydrocarbons with sunlight',D:'CO₂'},
ans:['C'],
trick:{text:'Photochemical smog = NOₓ + hydrocarbons + SUNLIGHT → ozone, PAN, etc. Los Angeles type smog.',formula:'NO₂ + UV → NO + O·\nO· + O₂ → O₃ (ozone)\nO₃ + hydrocarbons → PAN (photochemical smog)',steps:['NOₓ from vehicle exhaust','Hydrocarbons from fuel combustion','Sunlight provides energy','Photochemical reactions form O₃, PAN','= Photochemical smog (Los Angeles type)'],time:8},
sol:'Photochemical smog (Los Angeles smog):\nNO₂ + UV light → NO + O (atomic)\nO + O₂ → O₃ (ozone)\nO₃ + hydrocarbons → PAN (peroxyacetyl nitrate), aldehydes\nMain precursors: NO₂ + hydrocarbons + sunlight\n✓ Answer: C'},

];

// ══════════════════════════════════════════════════════
// CHAPTER FREQUENCY DATA
// ══════════════════════════════════════════════════════
const CHAPTER_FREQ = [
  {subject:'math',   color:'#ef4444', chapter:'Calculus',              count:48, pct:85},
  {subject:'math',   color:'#ef4444', chapter:'Coordinate Geometry',   count:38, pct:72},
  {subject:'math',   color:'#ef4444', chapter:'Algebra',               count:35, pct:68},
  {subject:'math',   color:'#ef4444', chapter:'Trigonometry',          count:28, pct:55},
  {subject:'math',   color:'#ef4444', chapter:'Probability',           count:20, pct:42},
  {subject:'math',   color:'#ef4444', chapter:'Vectors & 3D',          count:22, pct:48},
  {subject:'physics',color:'#6366f1', chapter:'Electrostatics',        count:32, pct:65},
  {subject:'physics',color:'#6366f1', chapter:'Current Electricity',   count:30, pct:62},
  {subject:'physics',color:'#6366f1', chapter:'Mechanics',             count:28, pct:58},
  {subject:'physics',color:'#6366f1', chapter:'Modern Physics',        count:26, pct:54},
  {subject:'physics',color:'#6366f1', chapter:'Optics',                count:22, pct:46},
  {subject:'physics',color:'#6366f1', chapter:'Waves',                 count:18, pct:38},
  {subject:'chem',   color:'#10b981', chapter:'Organic Chemistry',     count:42, pct:80},
  {subject:'chem',   color:'#10b981', chapter:'Physical Chemistry',    count:36, pct:70},
  {subject:'chem',   color:'#10b981', chapter:'Chemical Bonding',      count:30, pct:60},
  {subject:'chem',   color:'#10b981', chapter:'Periodic Table',        count:20, pct:44},
  {subject:'chem',   color:'#10b981', chapter:'Electrochemistry',      count:18, pct:40},
];

// ══════════════════════════════════════════════════════
// QUICK TRICKS LIBRARY
// ══════════════════════════════════════════════════════
const QUICK_TRICKS = [
  {subject:'math',  title:'AP n-th term from Sₙ',         text:'T_n = S_n - S_{n-1}. For quadratic Sₙ = an²+bn, T_n = a(2n-1)+b.',formula:'T_n = S_n - S_{n-1}',time:8},
  {subject:'math',  title:'Vieta\'s Formulas',             text:'For x²+bx+c=0: sum of roots = -b, product = c. No need to solve!',formula:'α+β = -b/a, αβ = c/a',time:6},
  {subject:'math',  title:'Integration by Parts',          text:'∫u dv = uv - ∫v du. LIATE rule: Logs, Inverse trig, Algebra, Trig, Exponential',formula:'∫u·dv = u·v - ∫v·du',time:5},
  {subject:'math',  title:'Circle chord/tangent',          text:'Equation of tangent to x²+y²=r² at point (x₁,y₁): xx₁+yy₁=r²',formula:'T = 0: xx₁+yy₁ = r²',time:8},
  {subject:'math',  title:'Number of terms in binomial',   text:'(a+b)ⁿ has exactly (n+1) terms. Simple!',formula:'Terms = n+1',time:4},
  {subject:'physics',title:'Terminal velocity shortcut',   text:'T.V. of falling sphere: v = 2r²(ρ-σ)g/9η. For relative density: proportional to r².',formula:'v_t = 2r²(ρ-ρ_f)g/9η',time:10},
  {subject:'physics',title:'Carnot efficiency',            text:'η = 1 - T_cold/T_hot. Always use absolute temperature (Kelvin)!',formula:'η = 1 - T_L/T_H',time:6},
  {subject:'physics',title:'Mirror formula mnemonic',      text:'1/v + 1/u = 1/f. Sign convention: all distances from pole; real = negative.',formula:'1/f = 1/v + 1/u',time:8},
  {subject:'physics',title:'Doppler frequency trick',      text:'Source approaching observer: denominator decreases → f increases. Moving away: denominator increases → f decreases.',formula:'f = f₀·(v±v_o)/(v∓v_s)',time:10},
  {subject:'physics',title:'Gauss law applications',       text:'For symmetric charge distributions, just count charge inside and divide by ε₀.',formula:'φ = Q_enc/ε₀',time:6},
  {subject:'chem',  title:'Hybridisation formula',         text:'H = ½(V+X-C+A). V=valence e⁻, X=monovalent atoms, C=+charge, A=-charge',formula:'H = ½(V+X-C+A)',time:8},
  {subject:'chem',  title:'First order t₁/₂',              text:'t₁/₂ = 0.693/k. Always constant for 1st order — independent of concentration!',formula:'t₁/₂ = 0.693/k',time:5},
  {subject:'chem',  title:'Faraday\'s electrolysis',       text:'W = ZIt = (M/nF)×It. For deposition: moles deposited = charge/(n×F)',formula:'m = M·I·t/(n·F)',time:10},
  {subject:'chem',  title:'Raoult\'s law',                 text:'p = p°·x (mole fraction). Vapour pressure lowering = p°×x_solute. Proportional to mole fraction!',formula:'Δp/p° = x_solute',time:8},
  {subject:'chem',  title:'pH quick calc',                 text:'pH = -log[H⁺]. For strong acid: [H⁺]=[acid]. 0.01M HCl → pH=2. 10⁻⿻M → pH=n',formula:'pH = -log₁₀[H⁺]',time:5},
];
